[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.2"

[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "62042cd3edd1d60787b765dcc2e863df6d0eb667"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  revision = "15c4be53659e613f7a85b967f3c5614da79ec4d1"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-kubernetes"
  source = "github.com/pulumi/terraform-provider-kubernetes"
  branch = "pulumi-master"

[[override]]
  name = "k8s.io/client-go"
  revision = "d92e8497f71b7b4e0494e5bd204b48d34bd6f254"

[[override]]
  revision = "1fd2e63a9a370677308a42f24fd40c86438afddf"
  name = "k8s.io/apimachinery"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"
