[[override]]
  name = "github.com/pulumi/pulumi"
  revision = "v0.12.0"

[[override]]
  name = "github.com/ugorji/go"
  revision = "8c0409fcbb70099c748d71f714529204975f6c3f"

[[override]]
  name = "github.com/cbroglie/mustache"
  revision = "v1.0.0"

# ---------------------------------------------------------------------------
# NOTE: the k8s.io dependencies, (including go-autorest) are highly sensitive
# to change! They are pinned at versions where (1) they compile (nb.,
# surprisingly challenging) and (2) their quirks are well-understood. cf.,
# [here][1], [here][2], and [here][3].
#
# [1]: https://medium.com/@andy.goldstein/upgrading-kubernetes-client-go-from-v4-to-v5-bbd5025fe381
# [2]: https://medium.com/@vladimirvivien/using-gos-dep-to-organize-your-kubernetes-client-go-dependencies-509ddc766ed3
# [3]: https://blog.heptio.com/straighten-out-your-kubernetes-client-go-dependencies-heptioprotip-8baeed46fe7d
# ---------------------------------------------------------------------------

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[[override]]
  name = "k8s.io/kubernetes"
  revision = "v1.10.2"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "ab5671379918d9af294b6f0e3d8aaa98c829416d"

# ---------------------------------------------------------------------------
# End sensitive k8s.io dependencies.
# ---------------------------------------------------------------------------

[[constraint]]
  name = "github.com/yudai/gojsondiff"
  revision = "9209d1532c51cabe0439993586a71c207b09a0ac"
