required = ["k8s.io/kubernetes/pkg/kubectl/cmd/util"]

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

#
# Kubernetes packages
#

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.13.1"

[[constraint]]
  name = "k8s.io/client-go"
  version = "10.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.0"

[[constraint]]
  name = "k8s.io/api"
  revision = "kubernetes-1.13.0"

[[override]]
  name = "sigs.k8s.io/kustomize"
  version = "1.0.11"

#
# Cloud provider packages
#

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.12"

# vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use json.Number(expiresIn) (type json.Number) as type string in field value
# vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
# vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:249:4: cannot use json.Number(expiresOn) (type json.Number) as type string in field value
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v11.1.0"

#
# Third party packages
#

[[constraint]]
  name = "github.com/cbroglie/mustache"
  version = "v1.0.0"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.5"

[[override]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[override]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[override]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

# vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.go:296:21: c.cc.NewStream undefined (type *grpc.ClientConn has no field or method NewStream)
# vendor/github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1/trace_service.pb.go:327:21: c.cc.NewStream undefined (type *grpc.ClientConn has no field or method NewStream)
[[override]]
  name = "google.golang.org/grpc"
  version = "1.18.0"
